### ISSUE TITLE
use shadows

### ISSUE THREAD

**Issue by kcyu2014** [princeton-computational-imaging/neural-scene-graphs#10]
Thanks for your great work and sharing your code to reconstruct the dynamic scene. 

I have seen the paper mentioning that the NSG can learn the shadow implicitly, and saw there is `use_shadows` in the arguments. However, this argument seems not to be used anywhere in the code base. Is this because the release version did not have such functionality?

Best,
Kaicheng

**Comment by ostjul** [comment]
Hello Kaicheng, this was just used for some experiments to extract shadows separately from the objects and background. Simple approaches weren't successful so it was not used in the released version or the published paper.
