### ISSUE TITLE
Black Background during training

### ISSUE THREAD

**Issue by hturki** [princeton-computational-imaging/neural-scene-graphs#15]
With certain train/test splits on Scenes 1 and 2 (using the settings in https://github.com/princeton-computational-imaging/neural-scene-graphs/issues/7) I see either a black background or nothing at all:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/868618/198194958-1850d67e-529b-43ca-ac3d-d7ae5cd11b15.png">

Any guidance on what could be causing this would be greatly appreciated!

**Comment by hturki** [comment]
I'm able to work around this by just trying out different seeds and finding one that works.

**Comment by jiahao-shao1** [comment]
Thank you so much! You saved my day. By the way, may I ask which seed was ultimately chosen for the training process？
