### ISSUE TITLE
How do we manipulate the scene graphs?

### ISSUE THREAD

**Issue by cinjon** [princeton-computational-imaging/neural-scene-graphs#4]
Hi there, where in the codebase is the scene graph backed out? And then also where is it manipulated afterward?
Thanks.

**Comment by ostjul** [comment]
Hi! No, the graph is not backed out expletliy and the relative poses are directly forwarded to the renderer. But you should be able to access manipulation with --manipulate for --render_only , which access the [manipulations](https://github.com/princeton-computational-imaging/neural-scene-graphs/blob/8d3d9ce9064ded8231a1374c3866f004a4a281f8/neural_scene_graph_manipulation.py#L46)
