### ISSUE TITLE
How many frames did you take for each sequence?

### ISSUE THREAD

**Issue by yjcaimeow** [princeton-computational-imaging/neural-scene-graphs#7]
@fheide @ostjul 

Hi all,
Could you tell me the number you used for each sequence? And only one for novel view synthesis?

Best,
Yingjie

**Comment by ostjul** [comment]
Hi Yingjie,

We used the following scenes and sequences from the KITTI dataset:
-     Scene 1: 380-431 (far_plane=100.)
-     Scene 2: 140-224 (far_plane=150.)
-     Scene 6: 0-20 + 65-120 (far_plane=150.)
 
and every thenth frame was excluded from training for the novel view synthesis experiments.

Best,
Julian
